### PR TITLE
Remove unused GetSetMixin

### PR DESCRIPTION
**Pull request by mlunoe**
GetSetMixin was not being used anywhere, so this PR removes it

### CODE REVIEW

**Comment by mlunoe** [comment]
@MatApple I know you looked at the other PR I had up, so maybe you could take a look at this as well?

**Comment by MatApple** [comment]
We have one internally in DCOS-UI too 😞 . Nice cleanup!

**Comment by mlunoe** [comment]
That has already been removed here: https://github.com/dcos/dcos-ui/pull/1073

:)

**Comment by MatApple** [comment]
I was just surprised we had one in this repo too!

**Pull request merged**
